version: "2"

linters:
  enable:
    - nilerr
    - promlinter
    - revive
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: package-comments
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dfioravanti/httpregistry
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
